fix KeyError by providing empty dict as default value
deftinc/feature_gate pull request #10
Opened 2024-03-25 14:20 UTC by vinbarnes

This fixes `KeyError 'data'` errors.

This switches access for the dict to use `.get()` and supplies a default value `{}` when the 'data' key is not present.

2024-03-25 14:31 UTC, thephw requested changes

2024-03-25 14:31 UTC, thephw commented on feature_gate/clients/posthog_api_client.py
> +    features = self.list_features().get("data", {})
```suggestion
    features = self.list_features().get("data", [])
```

2024-03-25 14:31 UTC, thephw commented on feature_gate/clients/posthog_api_client.py
> +    features = self.list_features().get("data", {})
I think data is an array of json objects.

2024-03-25 14:31 UTC, thephw commented on feature_gate/clients/posthog_api_client.py
> +    features = self.list_features().get("data", {})
https://github.com/deftinc/feature_gate/blob/main/tests/fixtures/posthog_api_client/get_features_when_funnel.json

2024-03-25 14:33 UTC, thephw commented on feature_gate/clients/posthog_api_client.py
> +    features = self.list_features().get("data", {})
https://github.com/deftinc/feature_gate/blob/main/feature_gate/clients/posthog_api_client.py#L226

2024-03-25 14:56 UTC, prontsevychev commented on feature_gate/clients/posthog_api_client.py
> +    features = self.list_features().get("data", {})
Default type is not critical here (itreate over empty dict or list are the same), but for data consistency - would be nice. If I understand correctly, this is only the case for errors. How do we handle `_map_error_response` ? Or are they just internal API errors and library users shouldn't care about them?

2024-03-26 02:05 UTC, vinbarnes commented on feature_gate/clients/posthog_api_client.py
> +    features = self.list_features().get("data", {})
> I think data is an array of json objects.

Right you are.

```
In [25]: flipper.adapter.client.list_features()
Out[25]:
{'data': [{'id': xxxxx,

   # snip

```

2024-03-26 02:11 UTC, vinbarnes commented on feature_gate/clients/posthog_api_client.py
> +    features = self.list_features().get("data", {})
> How do we handle `_map_error_response` ?

Good question. I don't know. Thoughts?

2024-03-26 02:26 UTC, vinbarnes commented on feature_gate/clients/posthog_api_client.py
> +    features = self.list_features().get("data", {})
Test added 8c2feac

2024-03-27 17:15 UTC, prontsevychev commented on tests/fixtures/posthog_api_client/mocks.py
> +def mock_features_when_error_returned():
Not blocker, just suggestion to improve. There is python library `responses` to mock all `requests` calls. Easy to configure and use. Here is link:
https://pypi.org/project/responses/

2024-03-27 17:15 UTC, prontsevychev commented on feature_gate/clients/posthog_api_client.py
> +    features = self.list_features().get("data", {})
> Good question. I don't know. Thoughts?

It depends on what kind of errors might occur and how to you want to handle them. If it's some internal API things, somebody must check logs and fix it ASAP (maybe add some notifications, emailing, Sentry). If something is related to PostHog account, you should probably pass it on to end user so they know about it and fix it. Like you are doing here, for example:
https://github.com/deftinc/feature_gate/blob/main/feature_gate/clients/posthog_api_client.py#L102

But with this `FeatureNotFound` we have another issue on client side, because our current realization of client code doesn't handle this error properly ("global" error handling with `except Exception` is usually bad, because it can cause hiding problems that should be fixed).

2024-03-27 17:15 UTC, prontsevychev commented on feature_gate/clients/posthog_api_client.py
> +    features = self.list_features().get("data", {})
Sorry, I have no such experience with creating libraries for users. So far I have only worked in projects' scope.

2024-04-11 13:13 UTC, vinbarnes commented
Regarding the discussion of where errors should be handled, we determined that the client code using this library is responsible. We may revisit this at a later date depending on usage.

2024-04-11 13:13 UTC, merged